#=============================================================================
#
# file :        Makefile
#
# description : Makefile to generate a TANGO device server.
#
# project :     SettingsManager
#
# $Author:  $
#
# $Revision:  $
# $Date:  $
#
#=============================================================================
#                This file is generated by POGO
#        (Program Obviously used to Generate tango Object)
#=============================================================================
#
#

#=============================================================================
#
CLASS	     = SettingsManager
PACKAGE      = org.tango.settingsmanager
HOME_SRC     = src/main/java/
SOURCE_FILES = org/tango/settingsmanager
MAJOR_VERS   = 3
MINOR_VERS   = 0
RELEASE      = $(MAJOR_VERS).$(MINOR_VERS)

#=============================================================================
# Generate documentation
#
DOC_DIR    = doc/classes
DOC_HEADER = "$(CLASS) API documention"
OVERVIEW   = ./overview.html
documentation:
	cd $(HOME_SRC); \
	javadoc \
	-version -author \
	-public \
	-windowtitle "$(CLASS) API" \
	-header $(DOC_HEADER) \
	-d      ../../../$(DOC_DIR) \
	-link . \
	-group "SettingsManager client classes"    "org.tango.settingsmanager.client" \
	-group "SettingsManager server classes"    "org.tango.settingsmanager" \
	\
	$(SOURCE_FILES)/client/SettingsManagerClient.java \
	$(SOURCE_FILES)/client/SettingsManagedEvent.java \
	$(SOURCE_FILES)/client/SettingsManagedListener.java \
	\
	$(SOURCE_FILES)/SettingsManager.java

