#=============================================================================
#
# file :        Makefile
#
# description : Makefile to generate a TANGO device server.
#
# project :     SettingsManager
#
# $Author:  $
#
# $Revision:  $
# $Date:  $
#
#=============================================================================
#                This file is generated by POGO
#        (Program Obviously used to Generate tango Object)
#=============================================================================
#
#

#=============================================================================
#
CLASS	     = SettingsManager
PACKAGE      = org.tango.settingsmanager
HOME_SRC     = src/main/java/
SOURCE_FILES = org/tango/settingsmanager
MAJOR_VERS   = 2
MINOR_VERS   = 8
RELEASE      = $(MAJOR_VERS).$(MINOR_VERS)

#=============================================================================
# Generate documentation
#
DOC_DIR    = doc/classes
DOC_HEADER = "$(CLASS) API documention"
OVERVIEW   = ./overview.html
documentation:
	cd $(HOME_SRC); \
	javadoc \
	-version -author \
	-public \
	-windowtitle "$(CLASS) API" \
	-header $(DOC_HEADER) \
	-d      ../../../$(DOC_DIR) \
	-link . \
	-group "SettingsManager client classes"    "org.tango.settingsmanager.client" \
	-group "SettingsManager server classes"    "org.tango.settingsmanager" \
	\
	$(SOURCE_FILES)/client/SettingsManagerClient.java \
	$(SOURCE_FILES)/client/SettingsManagedEvent.java \
	$(SOURCE_FILES)/client/SettingsManagedListener.java \
	\
	$(SOURCE_FILES)/SettingsManager.java




TANGO_JAVA=$(TANGO_HOME)/release/java
CLP=$(TANGO_JAVA)/appli/Pogo.jar
UPDATE_CLASS =  org.tango.pogo.pogo_gui.tools.UpdateRelease
version:
	@echo "-----------------------------------------"
	@echo "	Patching Version"
	@echo "-----------------------------------------"
	echo "Updating date and revision number..."
	java -cp $(CLP) $(UPDATE_CLASS) \
		-file $(HOME_SRC)/$(SOURCE_FILES)/commons/ICommons.java \
		-release $(RELEASE) \
		-title   "$(CLASS) Release Notes" \
		-note_path $(HOME_SRC)/$(SOURCE_FILES)/commons \
		-package $(PACKAGE).commons
		

JTANGO = $(TANGO_HOME)/release/java/lib/JTango.jar
run:
	java -cp target/classes/:$(JTANGO) $(PACKAGE).$(CLASS) test
