
package org.tango.settingsmanager.commons;

/**
 * HTML code to display Release Notes for this package.
 * It is generated by Pogo classes from a text file.
 */

public interface ReleaseNote {
	String str = 
		"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2//EN\">\n" + 
		"<html>\n" + 
		"<head>\n" + 
		"<title> Release Note </title>\n" + 
		"</head>\n" + 
		"<body text=\"#000000\" bgColor=\"#FFFFFF\" link=\"#0000FF\" vLink=\"#7F00FF\" aLink=\"#FF0000\">\n" + 
		"<p><!-------TITLE------></p>\n" + 
		"<center>	<h2>SettingsManager Release Notes </h2>\n" + 
		"	(Generated 12-10-2017  10:59:54)</center><br>\n" + 
		"<li><b>SettingManager-2.4 - 12/10/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix bug if LastAppliedfile not found at startup.<br>" + 
		"&nbsp; &nbsp; &nbsp; Re organize SettingsManagerPanel class.<br>" + 
		"<li><b>SettingManager-2.3 - 29/09/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve status message<br>" + 
		"<li><b>SettingManager-2.2 - 28/09/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem in threads synchronization.<br>" + 
		"<li><b>SettingManager-2.1 - 18/09/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem when generate and reload file for check changes.<br>" + 
		"<li><b>SettingManager-2.0 - 13/09/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; LastAppliedFile is now memorized.<br>" + 
		"<li><b>SettingManager-1.9 - 10/05/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add some methods to customize file browser.<br>" + 
		"<li><b>SettingManager-1.8 - 10/05/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem with java1.8 to display very long line.<br>" + 
		"<li><b>SettingManager-1.7 - 24/01/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a bug in settings format.<br>" + 
		"&nbsp; &nbsp; &nbsp; Add a DebugRootPath environment variable.<br>" + 
		"<li><b>SettingManager-1.6 - 12/01/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Force polling for State and Status.<br>" + 
		"<li><b>SettingManager-1.5 - 09/12/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Moved to git and adapted to maven<br>" + 
		"<li><b>SettingManager-1.4 - 14/09/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add a thread to server to check if settings have changed since last applied.<br>" + 
		"<li><b>SettingManager-1.3 - 20/06/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a little bug in client file selection.<br>" + 
		"<li><b>SettingManager-1.2 - 06/06/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; A timeout on settings added.<br>" + 
		"<li><b>SettingManager-1.1 - 13/04/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; A JTree file browser added.<br>" + 
		"<li><b>SettingManager-1.0 - 24/03/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Initial revision<br>" + 
		"</body>\n" + 
		"</html>\n"
	;
}