
package org.tango.settingsmanager.commons;

/**
 * HTML code to display Release Notes for this package.
 * It is generated by Pogo classes from a text file.
 */

public interface ReleaseNotes {
	String htmlString = 
		"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2//EN\">\n" + 
		"<html>\n" + 
		"<head>\n" + 
		"<title> Release Notes </title>\n" + 
		"</head>\n" + 
		"<body text=\"#000000\" bgColor=\"#FFFFFF\" link=\"#0000FF\" vLink=\"#7F00FF\" aLink=\"#FF0000\">\n" + 
		"<p><!-------TITLE------></p>\n" + 
		"<center><h2> Release Notes </h2>\n" + 
		"generated: 17-02-2021  10:18</center>\n" + 
		"<li><b>SettingManager-4.1 - 17/02/21:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Support for multiple lines comments<br>" + 
		"<li><b>SettingManager-4.0 - 19/12/19:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add an asynchronous mode to apply settings (AsynchronousApply property)<br>" + 
		"<li><b>SettingManager-3.2 - 28/06/19:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a bug when format is not specified<br>" + 
		"<li><b>SettingManager-3.1 - 03/12/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; ApplyAnyWay property added.<br>" + 
		"<li><b>SettingManager-3.0 - 04/12/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Manage display_unit attribute in generating settings file.<br>" + 
		"<li><b>SettingManager-2.7 - 16/10/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add a property to forget changes checks.<br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a bug when file starts with project name.<br>" + 
		"<li><b>SettingManager-2.4 - 12/10/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix bug if LastAppliedfile not found at startup.<br>" + 
		"&nbsp; &nbsp; &nbsp; Re organize SettingsManagerPanel class.<br>" + 
		"<li><b>SettingManager-2.3 - 29/09/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve status message<br>" + 
		"<li><b>SettingManager-2.2 - 28/09/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem in threads synchronization.<br>" + 
		"<li><b>SettingManager-2.1 - 18/09/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem when generate and reload file for check changes.<br>" + 
		"<li><b>SettingManager-2.0 - 13/09/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; LastAppliedFile is now memorized.<br>" + 
		"<li><b>SettingManager-1.9 - 10/05/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add some methods to customize file browser.<br>" + 
		"<li><b>SettingManager-1.8 - 10/05/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a problem with java1.8 to display very long line.<br>" + 
		"<li><b>SettingManager-1.7 - 24/01/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a bug in settings format.<br>" + 
		"&nbsp; &nbsp; &nbsp; Add a DebugRootPath environment variable.<br>" + 
		"<li><b>SettingManager-1.6 - 12/01/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Force polling for State and Status.<br>" + 
		"<li><b>SettingManager-1.5 - 09/12/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Moved to git and adapted to maven<br>" + 
		"<li><b>SettingManager-1.4 - 14/09/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add a thread to server to check if settings have changed since last applied.<br>" + 
		"<li><b>SettingManager-1.3 - 20/06/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a little bug in client file selection.<br>" + 
		"<li><b>SettingManager-1.2 - 06/06/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; A timeout on settings added.<br>" + 
		"<li><b>SettingManager-1.1 - 13/04/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; A JTree file browser added.<br>" + 
		"<li><b>SettingManager-1.0 - 24/03/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Initial revision<br>" + 
		"</body>\n" + 
		"</html>\n"
	;
}