
package org.tango.settingsmanager.commons;

/**
 * HTML code to display Release Notes for this package.
 * It is generated by Pogo classes from a text file.
 */

public interface ReleaseNote {
	String str = 
		"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2//EN\">\n" + 
		"<html>\n" + 
		"<head>\n" + 
		"<title> Release Note </title>\n" + 
		"</head>\n" + 
		"<body text=\"#000000\" bgColor=\"#FFFFFF\" link=\"#0000FF\" vLink=\"#7F00FF\" aLink=\"#FF0000\">\n" + 
		"<p><!-------TITLE------></p>\n" + 
		"<center>	<h2>SettingsManager Release Notes </h2>\n" + 
		"	(Generated 09-12-2016  09:08:47)</center><br>\n" + 
		"<li><b>SettingManager-1.5 - 09/12/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Moved to git and adapted to maven<br>" + 
		"<li><b>SettingManager-1.4 - 14/09/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Add a thread to server to check if settings have changed since last applied.<br>" + 
		"<li><b>SettingManager-1.3 - 20/06/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Fix a little bug in client file selection.<br>" + 
		"<li><b>SettingManager-1.2 - 06/06/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; A timeout on settings added.<br>" + 
		"<li><b>SettingManager-1.1 - 13/04/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; A JTree file browser added.<br>" + 
		"<li><b>SettingManager-1.0 - 24/03/16:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Initial revision<br>" + 
		"</body>\n" + 
		"</html>\n"
	;
}